apiVersion: v1
data:
  password: ZmMxNGUzOGIwYzg1MTM5NjlhNGM0ZDk1OWE4NzE2YzZkZDcxYmZlMQ==
  username: b2lyaWNhdWQ=
kind: Secret
metadata:
  name: pipeline-server-git
  namespace: kabanero
type: kubernetes.io/basic-auth
