apiVersion: v1
data:
  SONARQUBE_URL: url
kind: ConfigMap
metadata:
  annotations:
    description: Config map to hold the url for sonarqube in the environment so that
      other components can access it
  labels:
    app: sonarqube
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/part-of: sonarqube
    app.kubernetes.io/version: 0.1.3
    chart: tool-config-0.1.3
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
    release: sonarqube
  name: sonarqube-config
  namespace: kabanero