apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-storefront-repo-automator-task
  namespace: kabanero
spec:
  inputs:
    params:
      - description: Specify the Github organization to deploy the microservices to
        name: github_org
        type: string
      - description: Specify the users' github initials
        name: github_initials
        type: string
      - default: 'docker.io/node:12-stretch'
        name: docker_image
        type: string
  steps:
    - args:
        - '-c'
        - >
          wget
          https://github.com/cli/cli/releases/download/v0.9.0/gh_0.9.0_linux_amd64.deb

          ls -la

          apt install git && dpkg -i gh_0.9.0_linux_amd64.deb

          gh version

          export GITHUB_TOKEN=12345

          git clone
          https://github.com/ibm-garage-ref-storefront/storefront-repo-automator

          cd storefront-repo-automator 

          pwd

          ls -la

          echo "Github Organization: " $github_org

          echo "Github Initials: " $github_initials

          initials=$github_initials org=$github_org ./run.sh
      command:
        - /bin/bash
      env:
        - name: github_initials
          value: $(inputs.params.github_initials)
        - name: github_org
          value: $(inputs.params.github_org)
      image: $(inputs.params.docker_image)
      name: clone-storefront-automator-repo
      resources: {}