apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-storefront-repo-automator-task
  namespace: kabanero
spec:
  inputs:
    params:
      - description: Specify the Github organization to deploy the microservices to
        name: github_org
        type: string
      - description: Specify the users' github initials
        name: github_initials
        type: string
      - description: Specify the users' github token
        name: github_token
        type: string  
      - default: 'yellocabins/storefront:v5'
        name: docker_image
        type: string
  steps:
    - args:
        - '-c'
        - |
          set -e


          ls -la

          gh version

          gh config set -h github.com oauth_token $github_token

          git clone https://github.com/ibm-garage-ref-storefront/storefront-repo-automator

          cd storefront-repo-automator 

          pwd
          ls -la

          echo "Github Organization: " $github_org

          echo "Github Initials: " $github_initials

          initials=${github_initials}"-"./run.sh
      command:
        - /bin/bash
      env:
        - name: github_token
          value: $(inputs.params.github_token)
        - name: github_initials
          value: $(inputs.params.github_initials)
        - name: github_org
          value: $(inputs.params.github_org)
      image: $(inputs.params.docker_image)
      name: clone-storefront-automator-repo
      resources: {}